// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Fi1hMfrlhpZ8yQNssVRMAjFHDonclmY',
    appId: '1:761632017821:web:74cda051b45c34cef2f374',
    messagingSenderId: '761632017821',
    projectId: 'flutterudemychatapp-a499f',
    authDomain: 'flutterudemychatapp-a499f.firebaseapp.com',
    storageBucket: 'flutterudemychatapp-a499f.firebasestorage.app',
    measurementId: 'G-5ZTFF9J0J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOnEkSQJKI3yL764hx-M68KpiVlJr5yys',
    appId: '1:761632017821:android:fdccbf36a6d04c9af2f374',
    messagingSenderId: '761632017821',
    projectId: 'flutterudemychatapp-a499f',
    storageBucket: 'flutterudemychatapp-a499f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzK9nmaT662T_rWXoUH45RMVceiGpBJQ8',
    appId: '1:761632017821:ios:7913569ab5e82217f2f374',
    messagingSenderId: '761632017821',
    projectId: 'flutterudemychatapp-a499f',
    storageBucket: 'flutterudemychatapp-a499f.firebasestorage.app',
    iosClientId:
        '761632017821-79rtf4jq35ighi20anh0fff5o19fdmhp.apps.googleusercontent.com',
    iosBundleId: 'com.okoye.socialapp',
  );
}
